# Generated by Django 4.2.8 on 2024-01-03 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="schooldetails",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scname", models.CharField(max_length=100)),
                ("sctrusty", models.CharField(max_length=50)),
                ("scprincipal", models.CharField(max_length=50)),
                ("studentcapacity", models.IntegerField()),
                ("schooladd", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="StdPresent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stdroll", models.IntegerField()),
                ("stdstandard", models.IntegerField()),
                ("stdspresent", models.CharField(max_length=20)),
                ("stddate", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sname", models.CharField(max_length=100)),
                ("sroll", models.IntegerField()),
                ("sgender", models.CharField(max_length=100)),
                ("sstandard", models.IntegerField()),
                ("ssubject", models.TextField()),
                ("scity", models.CharField(max_length=50)),
                (
                    "scid",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="studentapp.schooldetails",
                    ),
                ),
            ],
        ),
    ]
