# Generated by Django 4.2.8 on 2024-01-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studentapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="sjoindate",
            field=models.DateField(default=None),
        ),
    ]
