# Generated by Django 4.2.8 on 2024-01-04 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studentapp", "0004_alter_student_sjoindate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="sjoindate",
            field=models.DateField(default="2002"),
        ),
    ]
