# Generated by Django 4.2.8 on 2024-01-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studentapp", "0005_alter_student_sjoindate"),
    ]

    operations = [
        migrations.RemoveField(model_name="student", name="sjoindate",),
        migrations.AddField(
            model_name="student",
            name="sjoindatw",
            field=models.DateField(blank=True, null=True),
        ),
    ]
