# Generated by Django 4.2.8 on 2024-01-04 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("studentapp", "0006_remove_student_sjoindate_student_sjoindatw"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student", old_name="sjoindatw", new_name="sjoindate",
        ),
    ]
