# Generated by Django 4.2.8 on 2024-01-04 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studentapp", "0009_alter_student_sjoindate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="sjoindate",
            field=models.DateField(blank=True, default="2002-05-05"),
        ),
    ]
