# Generated by Django 4.2.8 on 2024-01-04 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studentapp", "0011_remove_student_sjoindate"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="sjoindate",
            field=models.CharField(default=2002, max_length=50),
            preserve_default=False,
        ),
    ]
