# Generated by Django 4.2.8 on 2024-01-04 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studentapp", "0012_student_sjoindate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="sjoindate",
            field=models.CharField(default="2002-05-05", max_length=50),
        ),
    ]
