# Generated by Django 4.2.8 on 2024-01-04 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("studentapp", "0013_alter_student_sjoindate"),
    ]

    operations = [
        migrations.RemoveField(model_name="student", name="sjoindate",),
    ]
