# Generated by Django 4.2.8 on 2024-01-04 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studentapp", "0014_remove_student_sjoindate"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="sjoindate",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
